# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dr7eB3dz6-pCtSZYXth9xxFrYR4k0WG0
"""

# streamlit_app.py

import streamlit as st
import numpy as np
import pandas as pd
import joblib

@st.cache_resource
def cargar_modelo():
    model = joblib.load("regression_model.pkl")
    scaler = joblib.load("regression_scaler.pkl")
    return model, scaler

model, scaler = cargar_modelo()

st.title("Predicción de Esperanza de Vida de Gatos")

campos = {
    "Age_in_years": st.number_input("Edad (años)", min_value=0.0, max_value=30.0, step=0.1),
    "Age_in_months": st.number_input("Edad (meses)", min_value=0.0, max_value=360.0, step=1.0),
    "Body_length": st.number_input("Longitud del cuerpo (cm)", min_value=10.0, max_value=100.0, step=1.0),
    "Weight": st.number_input("Peso (kg)", min_value=0.5, max_value=20.0, step=0.1),
    "Owner_play_time_minutes": st.number_input("Minutos de juego diario", min_value=0.0, max_value=300.0, step=1.0),
    "Sleep_time_hours": st.number_input("Horas de sueño diario", min_value=0.0, max_value=24.0, step=0.5),
    "Latitude": st.number_input("Latitud", min_value=-90.0, max_value=90.0, step=0.1),
    "Longitude": st.number_input("Longitud", min_value=-180.0, max_value=180.0, step=0.1),
}

if st.button("Predecir Esperanza de Vida"):
    input_data = pd.DataFrame([campos])
    input_scaled = scaler.transform(input_data)
    pred = model.predict(input_scaled).flatten()[0]
    st.success(f"La esperanza de vida estimada es de: **{pred:.2f} años**")